# Generated by Django 2.1.1 on 2018-10-15 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('barracks_status_dire', models.CharField(blank=True, max_length=255)),
                ('barracks_status_radiant', models.CharField(blank=True, max_length=255)),
                ('chat', models.TextField(blank=True)),
                ('cluster', models.CharField(blank=True, max_length=255)),
                ('cosmetics', models.CharField(blank=True, max_length=255)),
                ('dire_score', models.CharField(blank=True, max_length=255)),
                ('draft_timings', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=255)),
                ('engine', models.CharField(blank=True, max_length=255)),
                ('first_blood_time', models.CharField(blank=True, max_length=255)),
                ('game_mode', models.CharField(blank=True, max_length=255)),
                ('human_players', models.CharField(blank=True, max_length=255)),
                ('leagueid', models.CharField(blank=True, max_length=255)),
                ('lobby_type', models.CharField(blank=True, max_length=255)),
                ('match_sequ_num', models.CharField(blank=True, max_length=255)),
                ('negative_votes', models.CharField(blank=True, max_length=255)),
                ('objectives', models.CharField(blank=True, max_length=255)),
                ('picks_bans', models.CharField(blank=True, max_length=255)),
                ('positive_votes', models.CharField(blank=True, max_length=255)),
                ('radiant_gold_adv', models.CharField(blank=True, max_length=255)),
                ('radiant_score', models.CharField(blank=True, max_length=255)),
                ('radiant_win', models.CharField(blank=True, max_length=255)),
                ('radiant_xp_adv', models.CharField(blank=True, max_length=255)),
                ('start_time', models.CharField(blank=True, max_length=255)),
                ('teamfights', models.CharField(blank=True, max_length=255)),
                ('tower_status_dire', models.CharField(blank=True, max_length=255)),
                ('tower_status_radiant', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=255)),
                ('replay_salt', models.CharField(blank=True, max_length=255)),
                ('series_id', models.CharField(blank=True, max_length=255)),
                ('series_type', models.CharField(blank=True, max_length=255)),
                ('radiant_team', models.CharField(blank=True, max_length=255)),
                ('dire_team', models.CharField(blank=True, max_length=255)),
                ('league', models.CharField(blank=True, max_length=255)),
                ('skill', models.CharField(blank=True, max_length=255)),
                ('players', models.TextField(blank=True)),
                ('patch', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('all_word_counts', models.CharField(blank=True, max_length=255)),
                ('throw', models.CharField(blank=True, max_length=255)),
                ('loss', models.CharField(blank=True, max_length=255)),
                ('win', models.CharField(blank=True, max_length=255)),
                ('replay_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('match_id',),
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AddField(
            model_name='player',
            name='account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='avatarfull',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='avatarmedium',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='cheese',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='created',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='player',
            name='is_contributor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_login',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='leaderboard_rank',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='loccountrycode',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mmr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='mmr_esitmated',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='personaname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='profileurl',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rank_tier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='steamid',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='dota2_id',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
