# Generated by Django 2.1.1 on 2018-10-15 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota2', '0003_auto_20181015_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created',
            field=models.DateTimeField(default=datetime.date(2018, 10, 15)),
        ),
    ]
