# Generated by Django 2.1.1 on 2018-10-15 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dota2', '0004_auto_20181015_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='openapi_hash',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
